// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvnyaxagaahibwyjtrdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2bnlheGFnYWFoaWJ3eWp0cmRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3OTM3NzQsImV4cCI6MjA1NDM2OTc3NH0.phm8tLPwqOVvXuT3OWNc8WBS-2xDPkLJl0Gk-hjeAuw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);